baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[menus]
  [[menus.header]]
    name = 'Accueil'
    url = 0
    weight = 
  [[menus.header]]
    name = 'Gribouille'
    url = '/contact'
    weight = 1
[[menus.header]]
    name = 'Écritouille'
    url = '/contact'
    weight = 2
[[menus.header]]
    name = 'Webouille'
    url = '/contact'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true