baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mon PF'

[menus]
  [[menus.header]]
    name = 'Accueil'
    url = '/'
    weight = 1
  [[menus.header]]
    name = 'Gribouille'
    url = '/contact'
    weight = 2
	[[menus.header]]
    name = 'Écritouille'
    url = '/contact'
    weight = 3
	[[menus.header]]
    name = 'Webouille'
    url = '/contact'
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        hardWraps = true